# Generated by Django 4.1.5 on 2023-03-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sstech', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/blogimages'),
        ),
    ]
