# Generated by Django 4.1.5 on 2023-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sstech', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
