# Generated by Django 4.1.5 on 2023-05-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sstech', '0005_alter_contact_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
